// Countries with flag emoji (UAE-20). Generated from Intl.DisplayNames so
// there's no data dependency; names are UPPERCASE to match how nationality is
// already stored ("BRAZIL", "UNITED STATES OF AMERICA"). Aliases added for the
// spellings UAEW uses that Intl grafts differently.
export interface Country { name: string; code: string; flag: string }

export const COUNTRIES: Country[] = [
  { name: 'AFGHANISTAN', code: 'AF', flag: '🇦🇫' },
  { name: 'ALBANIA', code: 'AL', flag: '🇦🇱' },
  { name: 'ALGERIA', code: 'DZ', flag: '🇩🇿' },
  { name: 'AMERICAN SAMOA', code: 'AS', flag: '🇦🇸' },
  { name: 'ANDORRA', code: 'AD', flag: '🇦🇩' },
  { name: 'ANGOLA', code: 'AO', flag: '🇦🇴' },
  { name: 'ANGUILLA', code: 'AI', flag: '🇦🇮' },
  { name: 'ANTARCTICA', code: 'AQ', flag: '🇦🇶' },
  { name: 'ANTIGUA & BARBUDA', code: 'AG', flag: '🇦🇬' },
  { name: 'ARGENTINA', code: 'AR', flag: '🇦🇷' },
  { name: 'ARMENIA', code: 'AM', flag: '🇦🇲' },
  { name: 'ARUBA', code: 'AW', flag: '🇦🇼' },
  { name: 'ASCENSION ISLAND', code: 'AC', flag: '🇦🇨' },
  { name: 'AUSTRALIA', code: 'AU', flag: '🇦🇺' },
  { name: 'AUSTRIA', code: 'AT', flag: '🇦🇹' },
  { name: 'AZERBAIJAN', code: 'AZ', flag: '🇦🇿' },
  { name: 'BAHAMAS', code: 'BS', flag: '🇧🇸' },
  { name: 'BAHRAIN', code: 'BH', flag: '🇧🇭' },
  { name: 'BANGLADESH', code: 'BD', flag: '🇧🇩' },
  { name: 'BARBADOS', code: 'BB', flag: '🇧🇧' },
  { name: 'BELARUS', code: 'BY', flag: '🇧🇾' },
  { name: 'BELGIUM', code: 'BE', flag: '🇧🇪' },
  { name: 'BELIZE', code: 'BZ', flag: '🇧🇿' },
  { name: 'BENIN', code: 'BJ', flag: '🇧🇯' },
  { name: 'BENIN', code: 'DY', flag: '🇩🇾' },
  { name: 'BERMUDA', code: 'BM', flag: '🇧🇲' },
  { name: 'BHUTAN', code: 'BT', flag: '🇧🇹' },
  { name: 'BOLIVIA', code: 'BO', flag: '🇧🇴' },
  { name: 'BOSNIA & HERZEGOVINA', code: 'BA', flag: '🇧🇦' },
  { name: 'BOTSWANA', code: 'BW', flag: '🇧🇼' },
  { name: 'BOUVET ISLAND', code: 'BV', flag: '🇧🇻' },
  { name: 'BRAZIL', code: 'BR', flag: '🇧🇷' },
  { name: 'BRITISH INDIAN OCEAN TERRITORY', code: 'IO', flag: '🇮🇴' },
  { name: 'BRITISH VIRGIN ISLANDS', code: 'VG', flag: '🇻🇬' },
  { name: 'BRUNEI', code: 'BN', flag: '🇧🇳' },
  { name: 'BULGARIA', code: 'BG', flag: '🇧🇬' },
  { name: 'BURKINA FASO', code: 'BF', flag: '🇧🇫' },
  { name: 'BURKINA FASO', code: 'HV', flag: '🇭🇻' },
  { name: 'BURUNDI', code: 'BI', flag: '🇧🇮' },
  { name: 'CAMBODIA', code: 'KH', flag: '🇰🇭' },
  { name: 'CAMEROON', code: 'CM', flag: '🇨🇲' },
  { name: 'CANADA', code: 'CA', flag: '🇨🇦' },
  { name: 'CANARY ISLANDS', code: 'IC', flag: '🇮🇨' },
  { name: 'CAPE VERDE', code: 'CV', flag: '🇨🇻' },
  { name: 'CARIBBEAN NETHERLANDS', code: 'BQ', flag: '🇧🇶' },
  { name: 'CAYMAN ISLANDS', code: 'KY', flag: '🇰🇾' },
  { name: 'CENTRAL AFRICAN REPUBLIC', code: 'CF', flag: '🇨🇫' },
  { name: 'CEUTA & MELILLA', code: 'EA', flag: '🇪🇦' },
  { name: 'CHAD', code: 'TD', flag: '🇹🇩' },
  { name: 'CHILE', code: 'CL', flag: '🇨🇱' },
  { name: 'CHINA', code: 'CN', flag: '🇨🇳' },
  { name: 'CHRISTMAS ISLAND', code: 'CX', flag: '🇨🇽' },
  { name: 'CLIPPERTON ISLAND', code: 'CP', flag: '🇨🇵' },
  { name: 'COCOS (KEELING) ISLANDS', code: 'CC', flag: '🇨🇨' },
  { name: 'COLOMBIA', code: 'CO', flag: '🇨🇴' },
  { name: 'COMOROS', code: 'KM', flag: '🇰🇲' },
  { name: 'CONGO - BRAZZAVILLE', code: 'CG', flag: '🇨🇬' },
  { name: 'CONGO - KINSHASA', code: 'CD', flag: '🇨🇩' },
  { name: 'CONGO - KINSHASA', code: 'ZR', flag: '🇿🇷' },
  { name: 'COOK ISLANDS', code: 'CK', flag: '🇨🇰' },
  { name: 'COSTA RICA', code: 'CR', flag: '🇨🇷' },
  { name: 'CÔTE D\'IVOIRE', code: 'CI', flag: '🇨🇮' },
  { name: 'CÔTE D’IVOIRE', code: 'CI', flag: '🇨🇮' },
  { name: 'CROATIA', code: 'HR', flag: '🇭🇷' },
  { name: 'CUBA', code: 'CU', flag: '🇨🇺' },
  { name: 'CURAÇAO', code: 'AN', flag: '🇦🇳' },
  { name: 'CURAÇAO', code: 'CW', flag: '🇨🇼' },
  { name: 'CYPRUS', code: 'CY', flag: '🇨🇾' },
  { name: 'CZECH REPUBLIC', code: 'CZ', flag: '🇨🇿' },
  { name: 'CZECHIA', code: 'CZ', flag: '🇨🇿' },
  { name: 'DEMOCRATIC REPUBLIC OF THE CONGO', code: 'CD', flag: '🇨🇩' },
  { name: 'DENMARK', code: 'DK', flag: '🇩🇰' },
  { name: 'DIEGO GARCIA', code: 'DG', flag: '🇩🇬' },
  { name: 'DJIBOUTI', code: 'DJ', flag: '🇩🇯' },
  { name: 'DOMINICA', code: 'DM', flag: '🇩🇲' },
  { name: 'DOMINICAN REPUBLIC', code: 'DO', flag: '🇩🇴' },
  { name: 'ECUADOR', code: 'EC', flag: '🇪🇨' },
  { name: 'EGYPT', code: 'EG', flag: '🇪🇬' },
  { name: 'EL SALVADOR', code: 'SV', flag: '🇸🇻' },
  { name: 'EQUATORIAL GUINEA', code: 'GQ', flag: '🇬🇶' },
  { name: 'ERITREA', code: 'ER', flag: '🇪🇷' },
  { name: 'ESTONIA', code: 'EE', flag: '🇪🇪' },
  { name: 'ESWATINI', code: 'SZ', flag: '🇸🇿' },
  { name: 'ETHIOPIA', code: 'ET', flag: '🇪🇹' },
  { name: 'EUROPEAN UNION', code: 'EU', flag: '🇪🇺' },
  { name: 'EUROZONE', code: 'EZ', flag: '🇪🇿' },
  { name: 'FALKLAND ISLANDS', code: 'FK', flag: '🇫🇰' },
  { name: 'FAROE ISLANDS', code: 'FO', flag: '🇫🇴' },
  { name: 'FIJI', code: 'FJ', flag: '🇫🇯' },
  { name: 'FINLAND', code: 'FI', flag: '🇫🇮' },
  { name: 'FRANCE', code: 'FR', flag: '🇫🇷' },
  { name: 'FRANCE', code: 'FX', flag: '🇫🇽' },
  { name: 'FRENCH GUIANA', code: 'GF', flag: '🇬🇫' },
  { name: 'FRENCH POLYNESIA', code: 'PF', flag: '🇵🇫' },
  { name: 'FRENCH SOUTHERN TERRITORIES', code: 'TF', flag: '🇹🇫' },
  { name: 'GABON', code: 'GA', flag: '🇬🇦' },
  { name: 'GAMBIA', code: 'GM', flag: '🇬🇲' },
  { name: 'GEORGIA', code: 'GE', flag: '🇬🇪' },
  { name: 'GERMANY', code: 'DD', flag: '🇩🇩' },
  { name: 'GERMANY', code: 'DE', flag: '🇩🇪' },
  { name: 'GHANA', code: 'GH', flag: '🇬🇭' },
  { name: 'GIBRALTAR', code: 'GI', flag: '🇬🇮' },
  { name: 'GREECE', code: 'GR', flag: '🇬🇷' },
  { name: 'GREENLAND', code: 'GL', flag: '🇬🇱' },
  { name: 'GRENADA', code: 'GD', flag: '🇬🇩' },
  { name: 'GUADELOUPE', code: 'GP', flag: '🇬🇵' },
  { name: 'GUAM', code: 'GU', flag: '🇬🇺' },
  { name: 'GUATEMALA', code: 'GT', flag: '🇬🇹' },
  { name: 'GUERNSEY', code: 'GG', flag: '🇬🇬' },
  { name: 'GUINEA', code: 'GN', flag: '🇬🇳' },
  { name: 'GUINEA-BISSAU', code: 'GW', flag: '🇬🇼' },
  { name: 'GUYANA', code: 'GY', flag: '🇬🇾' },
  { name: 'HAITI', code: 'HT', flag: '🇭🇹' },
  { name: 'HEARD & MCDONALD ISLANDS', code: 'HM', flag: '🇭🇲' },
  { name: 'HONDURAS', code: 'HN', flag: '🇭🇳' },
  { name: 'HONG KONG', code: 'HK', flag: '🇭🇰' },
  { name: 'HONG KONG SAR CHINA', code: 'HK', flag: '🇭🇰' },
  { name: 'HUNGARY', code: 'HU', flag: '🇭🇺' },
  { name: 'ICELAND', code: 'IS', flag: '🇮🇸' },
  { name: 'INDIA', code: 'IN', flag: '🇮🇳' },
  { name: 'INDONESIA', code: 'ID', flag: '🇮🇩' },
  { name: 'IRAN', code: 'IR', flag: '🇮🇷' },
  { name: 'IRAQ', code: 'IQ', flag: '🇮🇶' },
  { name: 'IRELAND', code: 'IE', flag: '🇮🇪' },
  { name: 'ISLE OF MAN', code: 'IM', flag: '🇮🇲' },
  { name: 'ISRAEL', code: 'IL', flag: '🇮🇱' },
  { name: 'ITALY', code: 'IT', flag: '🇮🇹' },
  { name: 'IVORY COAST', code: 'CI', flag: '🇨🇮' },
  { name: 'JAMAICA', code: 'JM', flag: '🇯🇲' },
  { name: 'JAPAN', code: 'JP', flag: '🇯🇵' },
  { name: 'JERSEY', code: 'JE', flag: '🇯🇪' },
  { name: 'JORDAN', code: 'JO', flag: '🇯🇴' },
  { name: 'KAZAKHSTAN', code: 'KZ', flag: '🇰🇿' },
  { name: 'KENYA', code: 'KE', flag: '🇰🇪' },
  { name: 'KIRIBATI', code: 'KI', flag: '🇰🇮' },
  { name: 'KOSOVO', code: 'XK', flag: '🇽🇰' },
  { name: 'KUWAIT', code: 'KW', flag: '🇰🇼' },
  { name: 'KYRGYZSTAN', code: 'KG', flag: '🇰🇬' },
  { name: 'LAOS', code: 'LA', flag: '🇱🇦' },
  { name: 'LATVIA', code: 'LV', flag: '🇱🇻' },
  { name: 'LEBANON', code: 'LB', flag: '🇱🇧' },
  { name: 'LESOTHO', code: 'LS', flag: '🇱🇸' },
  { name: 'LIBERIA', code: 'LR', flag: '🇱🇷' },
  { name: 'LIBYA', code: 'LY', flag: '🇱🇾' },
  { name: 'LIECHTENSTEIN', code: 'LI', flag: '🇱🇮' },
  { name: 'LITHUANIA', code: 'LT', flag: '🇱🇹' },
  { name: 'LUXEMBOURG', code: 'LU', flag: '🇱🇺' },
  { name: 'MACAO SAR CHINA', code: 'MO', flag: '🇲🇴' },
  { name: 'MADAGASCAR', code: 'MG', flag: '🇲🇬' },
  { name: 'MALAWI', code: 'MW', flag: '🇲🇼' },
  { name: 'MALAYSIA', code: 'MY', flag: '🇲🇾' },
  { name: 'MALDIVES', code: 'MV', flag: '🇲🇻' },
  { name: 'MALI', code: 'ML', flag: '🇲🇱' },
  { name: 'MALTA', code: 'MT', flag: '🇲🇹' },
  { name: 'MARSHALL ISLANDS', code: 'MH', flag: '🇲🇭' },
  { name: 'MARTINIQUE', code: 'MQ', flag: '🇲🇶' },
  { name: 'MAURITANIA', code: 'MR', flag: '🇲🇷' },
  { name: 'MAURITIUS', code: 'MU', flag: '🇲🇺' },
  { name: 'MAYOTTE', code: 'YT', flag: '🇾🇹' },
  { name: 'MEXICO', code: 'MX', flag: '🇲🇽' },
  { name: 'MICRONESIA', code: 'FM', flag: '🇫🇲' },
  { name: 'MOLDOVA', code: 'MD', flag: '🇲🇩' },
  { name: 'MONACO', code: 'MC', flag: '🇲🇨' },
  { name: 'MONGOLIA', code: 'MN', flag: '🇲🇳' },
  { name: 'MONTENEGRO', code: 'ME', flag: '🇲🇪' },
  { name: 'MONTSERRAT', code: 'MS', flag: '🇲🇸' },
  { name: 'MOROCCO', code: 'MA', flag: '🇲🇦' },
  { name: 'MOZAMBIQUE', code: 'MZ', flag: '🇲🇿' },
  { name: 'MYANMAR (BURMA)', code: 'BU', flag: '🇧🇺' },
  { name: 'MYANMAR (BURMA)', code: 'MM', flag: '🇲🇲' },
  { name: 'NAMIBIA', code: 'NA', flag: '🇳🇦' },
  { name: 'NAURU', code: 'NR', flag: '🇳🇷' },
  { name: 'NEPAL', code: 'NP', flag: '🇳🇵' },
  { name: 'NETHERLANDS', code: 'NL', flag: '🇳🇱' },
  { name: 'NEW CALEDONIA', code: 'NC', flag: '🇳🇨' },
  { name: 'NEW ZEALAND', code: 'NZ', flag: '🇳🇿' },
  { name: 'NICARAGUA', code: 'NI', flag: '🇳🇮' },
  { name: 'NIGER', code: 'NE', flag: '🇳🇪' },
  { name: 'NIGERIA', code: 'NG', flag: '🇳🇬' },
  { name: 'NIUE', code: 'NU', flag: '🇳🇺' },
  { name: 'NORFOLK ISLAND', code: 'NF', flag: '🇳🇫' },
  { name: 'NORTH KOREA', code: 'KP', flag: '🇰🇵' },
  { name: 'NORTH MACEDONIA', code: 'MK', flag: '🇲🇰' },
  { name: 'NORTHERN MARIANA ISLANDS', code: 'MP', flag: '🇲🇵' },
  { name: 'NORWAY', code: 'NO', flag: '🇳🇴' },
  { name: 'OMAN', code: 'OM', flag: '🇴🇲' },
  { name: 'OUTLYING OCEANIA', code: 'QO', flag: '🇶🇴' },
  { name: 'PAKISTAN', code: 'PK', flag: '🇵🇰' },
  { name: 'PALAU', code: 'PW', flag: '🇵🇼' },
  { name: 'PALESTINE STATE', code: 'PS', flag: '🇵🇸' },
  { name: 'PALESTINIAN TERRITORIES', code: 'PS', flag: '🇵🇸' },
  { name: 'PANAMA', code: 'PA', flag: '🇵🇦' },
  { name: 'PAPUA NEW GUINEA', code: 'PG', flag: '🇵🇬' },
  { name: 'PARAGUAY', code: 'PY', flag: '🇵🇾' },
  { name: 'PERU', code: 'PE', flag: '🇵🇪' },
  { name: 'PHILIPPINES', code: 'PH', flag: '🇵🇭' },
  { name: 'PITCAIRN ISLANDS', code: 'PN', flag: '🇵🇳' },
  { name: 'POLAND', code: 'PL', flag: '🇵🇱' },
  { name: 'PORTUGAL', code: 'PT', flag: '🇵🇹' },
  { name: 'PSEUDO-ACCENTS', code: 'XA', flag: '🇽🇦' },
  { name: 'PSEUDO-BIDI', code: 'XB', flag: '🇽🇧' },
  { name: 'PUERTO RICO', code: 'PR', flag: '🇵🇷' },
  { name: 'QATAR', code: 'QA', flag: '🇶🇦' },
  { name: 'RÉUNION', code: 'RE', flag: '🇷🇪' },
  { name: 'ROMANIA', code: 'RO', flag: '🇷🇴' },
  { name: 'RUSSIA', code: 'RU', flag: '🇷🇺' },
  { name: 'RUSSIA', code: 'SU', flag: '🇸🇺' },
  { name: 'RWANDA', code: 'RW', flag: '🇷🇼' },
  { name: 'SAMOA', code: 'WS', flag: '🇼🇸' },
  { name: 'SAN MARINO', code: 'SM', flag: '🇸🇲' },
  { name: 'SÃO TOMÉ & PRÍNCIPE', code: 'ST', flag: '🇸🇹' },
  { name: 'SARK', code: 'CQ', flag: '🇨🇶' },
  { name: 'SAUDI ARABIA', code: 'SA', flag: '🇸🇦' },
  { name: 'SENEGAL', code: 'SN', flag: '🇸🇳' },
  { name: 'SERBIA', code: 'CS', flag: '🇨🇸' },
  { name: 'SERBIA', code: 'RS', flag: '🇷🇸' },
  { name: 'SERBIA', code: 'YU', flag: '🇾🇺' },
  { name: 'SEYCHELLES', code: 'SC', flag: '🇸🇨' },
  { name: 'SIERRA LEONE', code: 'SL', flag: '🇸🇱' },
  { name: 'SINGAPORE', code: 'SG', flag: '🇸🇬' },
  { name: 'SINT MAARTEN', code: 'SX', flag: '🇸🇽' },
  { name: 'SLOVAKIA', code: 'SK', flag: '🇸🇰' },
  { name: 'SLOVENIA', code: 'SI', flag: '🇸🇮' },
  { name: 'SOLOMON ISLANDS', code: 'SB', flag: '🇸🇧' },
  { name: 'SOMALIA', code: 'SO', flag: '🇸🇴' },
  { name: 'SOUTH AFRICA', code: 'ZA', flag: '🇿🇦' },
  { name: 'SOUTH GEORGIA & SOUTH SANDWICH ISLANDS', code: 'GS', flag: '🇬🇸' },
  { name: 'SOUTH KOREA', code: 'KR', flag: '🇰🇷' },
  { name: 'SOUTH SUDAN', code: 'SS', flag: '🇸🇸' },
  { name: 'SPAIN', code: 'ES', flag: '🇪🇸' },
  { name: 'SRI LANKA', code: 'LK', flag: '🇱🇰' },
  { name: 'ST. BARTHÉLEMY', code: 'BL', flag: '🇧🇱' },
  { name: 'ST. HELENA', code: 'SH', flag: '🇸🇭' },
  { name: 'ST. KITTS & NEVIS', code: 'KN', flag: '🇰🇳' },
  { name: 'ST. LUCIA', code: 'LC', flag: '🇱🇨' },
  { name: 'ST. MARTIN', code: 'MF', flag: '🇲🇫' },
  { name: 'ST. PIERRE & MIQUELON', code: 'PM', flag: '🇵🇲' },
  { name: 'ST. VINCENT & GRENADINES', code: 'VC', flag: '🇻🇨' },
  { name: 'SUDAN', code: 'SD', flag: '🇸🇩' },
  { name: 'SURINAME', code: 'SR', flag: '🇸🇷' },
  { name: 'SVALBARD & JAN MAYEN', code: 'SJ', flag: '🇸🇯' },
  { name: 'SWEDEN', code: 'SE', flag: '🇸🇪' },
  { name: 'SWITZERLAND', code: 'CH', flag: '🇨🇭' },
  { name: 'SYRIA', code: 'SY', flag: '🇸🇾' },
  { name: 'TAIWAN', code: 'TW', flag: '🇹🇼' },
  { name: 'TAJIKISTAN', code: 'TJ', flag: '🇹🇯' },
  { name: 'TANZANIA', code: 'TZ', flag: '🇹🇿' },
  { name: 'THAILAND', code: 'TH', flag: '🇹🇭' },
  { name: 'TIMOR-LESTE', code: 'TL', flag: '🇹🇱' },
  { name: 'TIMOR-LESTE', code: 'TP', flag: '🇹🇵' },
  { name: 'TOGO', code: 'TG', flag: '🇹🇬' },
  { name: 'TOKELAU', code: 'TK', flag: '🇹🇰' },
  { name: 'TONGA', code: 'TO', flag: '🇹🇴' },
  { name: 'TRINIDAD & TOBAGO', code: 'TT', flag: '🇹🇹' },
  { name: 'TRISTAN DA CUNHA', code: 'TA', flag: '🇹🇦' },
  { name: 'TUNISIA', code: 'TN', flag: '🇹🇳' },
  { name: 'TURKEY', code: 'TR', flag: '🇹🇷' },
  { name: 'TÜRKIYE', code: 'TR', flag: '🇹🇷' },
  { name: 'TURKMENISTAN', code: 'TM', flag: '🇹🇲' },
  { name: 'TURKS & CAICOS ISLANDS', code: 'TC', flag: '🇹🇨' },
  { name: 'TUVALU', code: 'TV', flag: '🇹🇻' },
  { name: 'U.S. OUTLYING ISLANDS', code: 'UM', flag: '🇺🇲' },
  { name: 'U.S. VIRGIN ISLANDS', code: 'VI', flag: '🇻🇮' },
  { name: 'UGANDA', code: 'UG', flag: '🇺🇬' },
  { name: 'UKRAINE', code: 'UA', flag: '🇺🇦' },
  { name: 'UNITED ARAB EMIRATES', code: 'AE', flag: '🇦🇪' },
  { name: 'UNITED KINGDOM', code: 'GB', flag: '🇬🇧' },
  { name: 'UNITED KINGDOM', code: 'UK', flag: '🇺🇰' },
  { name: 'UNITED NATIONS', code: 'UN', flag: '🇺🇳' },
  { name: 'UNITED STATES', code: 'US', flag: '🇺🇸' },
  { name: 'UNITED STATES OF AMERICA', code: 'US', flag: '🇺🇸' },
  { name: 'UNKNOWN REGION', code: 'ZZ', flag: '🇿🇿' },
  { name: 'URUGUAY', code: 'UY', flag: '🇺🇾' },
  { name: 'UZBEKISTAN', code: 'UZ', flag: '🇺🇿' },
  { name: 'VANUATU', code: 'NH', flag: '🇳🇭' },
  { name: 'VANUATU', code: 'VU', flag: '🇻🇺' },
  { name: 'VATICAN CITY', code: 'VA', flag: '🇻🇦' },
  { name: 'VENEZUELA', code: 'VE', flag: '🇻🇪' },
  { name: 'VIETNAM', code: 'VD', flag: '🇻🇩' },
  { name: 'VIETNAM', code: 'VN', flag: '🇻🇳' },
  { name: 'WALLIS & FUTUNA', code: 'WF', flag: '🇼🇫' },
  { name: 'WESTERN SAHARA', code: 'EH', flag: '🇪🇭' },
  { name: 'YEMEN', code: 'YD', flag: '🇾🇩' },
  { name: 'YEMEN', code: 'YE', flag: '🇾🇪' },
  { name: 'ZAMBIA', code: 'ZM', flag: '🇿🇲' },
  { name: 'ZIMBABWE', code: 'RH', flag: '🇷🇭' },
  { name: 'ZIMBABWE', code: 'ZW', flag: '🇿🇼' },
];

/** The flag emoji for a stored nationality string, or a globe when unknown. */
export function flagFor(nationality: string | null | undefined): string {
  if (!nationality) return '🌐';
  const hit = COUNTRIES.find(c => c.name === nationality.trim().toUpperCase());
  return hit?.flag ?? '🌐';
}
